### ISSUE TITLE
Reqeust Reference Materials

### ISSUE THREAD

**Issue by kwansikkim** [akyidrian/abs#1]
Dear Project Maintainer,

Thank you for the sharing source code of ABS. I've studied the source code to understand the safety-critical system.
Could you share the reference materials in terms of specifications or requirements related to this project, if you have and it is possible?

Sincerely,
Kwansik

**Comment by akyidrian** [comment]
Hi Kwansik,

The code in this project is for educational purposes only, and it's not actively maintained. I no longer have the material you are after and even if I did I wouldn't be able to share it with you; sorry and good luck.

Thanks
